Repository teamcubation/byma-sbx-acciones, pull requests merged in 2024-10, with the labels that each got.

#1 Scaffolding inicial del proyecto
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/teamcubation/AccionService/AccionServiceApplication.java
  src/main/java/com/teamcubation/AccionService/application/port/in/.gitkeep
  src/main/java/com/teamcubation/AccionService/application/port/out/.gitkeep
  src/main/java/com/teamcubation/AccionService/application/service/.gitkeep
  src/main/java/com/teamcubation/AccionService/domain/exception/.gitkeep
  src/main/java/com/teamcubation/AccionService/domain/model/Accion.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/.gitkeep
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/entity/.gitkeep
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/repository/.gitkeep
  src/main/resources/application.properties
  src/test/java/com/teamcubation/AccionService/AccionServiceApplicationTests.java
Labels: Review effort [1-5]: 4

#4 Implementar repository
  src/main/java/com/teamcubation/AccionService/application/port/in/.gitkeep
  src/main/java/com/teamcubation/AccionService/application/port/out/.gitkeep
  src/main/java/com/teamcubation/AccionService/application/port/out/StockRepositoryPort.java
  src/main/java/com/teamcubation/AccionService/domain/model/Stock.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/entity/.gitkeep
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/entity/StockEntity.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/mapper/StockMapper.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/repository/.gitkeep
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/repository/SpringStockRepository.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/repository/StockRepositoryAdapter.java
Labels: Review effort [1-5]: 4

#7 Dockerfile
  Dockerfile
Labels: Review effort [1-5]: 2

#10 Documentación
  README.md
  pom.xml
  postman_test_collection.json
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/StockController.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/dto/EditedStockDTO.java
Labels: Review effort [1-5]: 3

#8 Conectar service con repository
  src/main/java/com/teamcubation/AccionService/application/port/in/StockInPort.java
  src/main/java/com/teamcubation/AccionService/application/port/out/StockOutPort.java
  src/main/java/com/teamcubation/AccionService/application/port/out/StockRepositoryPort.java
  src/main/java/com/teamcubation/AccionService/application/service/StockService.java
  src/main/java/com/teamcubation/AccionService/domain/exception/InvalidStockEntityException.java
  src/main/java/com/teamcubation/AccionService/exception/GlobalExceptionHandler.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/mapper/StockMapper.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/repository/StockOutAdapter.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/util/validation/OutValidation.java
Labels: Review effort [1-5]: 4

#13 Fix controller
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/StockController.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/impl/StockControllerImpl.java
Labels: Review effort [1-5]: 2

#14 Ultimos detalles de la app - app funcionando
  src/main/java/com/teamcubation/AccionService/application/service/util/validation/ServiceValidation.java
  src/main/java/com/teamcubation/AccionService/config/AppConfiguration.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/StockController.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/dto/StockRequestDTO.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/impl/StockControllerImpl.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/out/persistance/repository/MockOutAdapter.java
  src/main/resources/application.properties
Labels: Review effort [1-5]: 4

#15 Fix documentacion
  README.md
  postman_test_collection.json
Labels: Review effort [1-5]: 2

#16 Mejoras controller
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/dto/EditedStockDTO.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/dto/UpdatedStockDTO.java
  src/main/java/com/teamcubation/AccionService/infrastructure/adapter/in/web/controller/impl/StockControllerImpl.java
Labels: Review effort [1-5]: 2
